# Generated by Django 5.2 on 2025-04-22 05:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=50, null=True, verbose_name='unit of measurement')),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='quantity')),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='reorder level')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('address', models.TextField(blank=True, verbose_name='address')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Mobile number must be 10 digits', regex='^\\d{10}$')], verbose_name='phone no')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='location')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now_add=True, verbose_name='order date')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received Complete'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api.supplier')),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('operational_status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='api.department')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_workshops', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('IDLE', 'Idle'), ('MAINTENANCE', 'Under Maintenance'), ('BROKEN', 'Broken Down')], default='IDLE', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('operator_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('operator_auto_remove_at', models.DateTimeField(blank=True, null=True)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to='api.workshop')),
            ],
            options={
                'ordering': ['workshop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='unit price')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='total price')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_materials', to='api.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_materials', to='api.order')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('order', 'material')},
            },
        ),
    ]
