# Generated by Django 5.2 on 2025-04-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_manufacturingprocess_productionline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufacturing_processes',
            field=models.ManyToManyField(blank=True, related_name='products', through='api.ProductProcess', to='api.manufacturingprocess', verbose_name='manufacturing processes'),
        ),
    ]
