# Generated by Django 5.2 on 2025-04-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_manufacturing_processes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productionschedule',
            old_name='uodated_at',
            new_name='updated_at',
        ),
    ]
