# Generated by Django 5.2 on 2025-04-30 20:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_uodated_at_productionschedule_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received Complete'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['supplier', 'status'], name='api_order_supplie_86818b_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermaterial',
            index=models.Index(fields=['order'], name='api_orderma_order_i_fbd0db_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermaterial',
            index=models.Index(fields=['material'], name='api_orderma_materia_3b1644_idx'),
        ),
    ]
