services:
  fms-database:
    image: postgres:14-alpine
    container_name: fms-database
    volumes:
      - fms-database-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.prod
    networks:
      - fms-network
    restart: unless-stopped

  fms-redis:
    image: redis:7-alpine
    container_name: fms-redis
    volumes:
      - fms-redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - fms-network
    restart: unless-stopped

  fms-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_CLIENT_ID=${VITE_CLIENT_ID}
    container_name: fms-frontend
    ports:
      - "5173:5173"
    env_file:
      - .env.prod
    networks:
      - fms-network
    restart: unless-stopped

  fms-proxy:
    image: nginx:1.25-alpine-slim
    container_name: fms-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - media-files:/app/media
    ports:
      - "80:80"
    networks:
      - fms-network

  fms-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fms-backend
    volumes:
      - media-files:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - fms-database
      - fms-redis
    networks:
      - fms-network
    restart: unless-stopped

networks:
  fms-network:
    driver: bridge

volumes:
  fms-database-data:
  fms-redis-data:
  media-files:
