# Generated by Django 5.2.9 on 2025-12-03 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_material_inventory_m_name_1014de_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='task name')),
                ('task_description', models.TextField(blank=True, null=True, verbose_name='task description')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='quantity used')),
                ('usage_date', models.DateTimeField(auto_now_add=True, verbose_name='usage date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to='inventory.material')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_date'],
                'indexes': [models.Index(fields=['material'], name='inventory_m_materia_1f7f00_idx'), models.Index(fields=['used_by'], name='inventory_m_used_by_4f0c04_idx'), models.Index(fields=['usage_date'], name='inventory_m_usage_d_6c3e5d_idx'), models.Index(fields=['task_name'], name='inventory_m_task_na_3bc81a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity_used__gt', 0)), name='material_usage_quantity_positive')],
            },
        ),
    ]
